### PR TITLE
Remove tk dependency for cli usage

### PR DESCRIPTION
**Pull request by phixtyseven**
* Wrap the import of guiMain in a try block
* Notify the user if Gui is missing required dependencies
  * Then report an error should the gui be explicitly requested

Also:
* Fix .gitignore to ignore ROMs saved into Output folder
  (Maybe this isn't an issue on Windows)
* Make OoTRandomizer executable

Closes AmazingAmpharos/OoT-Randomizer#40

### CODE REVIEW

**Comment by phixtyseven** [comment]
Good idea, I'll fix that when I have a minute.

**Comment by phixtyseven** [comment]
For future reference, should I be committing here? There seems to be a lot of activity on TestRunner's fork as well. It's unclear to me what the reasoning is; both repos appear to be on the same path.

**Comment by phixtyseven** [comment]
Oh I see. Thanks!

**Comment by phixtyseven** [comment]
Eyy, @flagrama:

This is unrelated here, but do you know where I can find help getting my feet wet in the assembly side of the project? I have a few ideas I'd like to tinker with, I just don't get the workflow (debugging, etc).

My current approach of modifying the decompiled rom and crossing my fingers has proven to be ineffective. ✌️

**Comment by flagrama** [comment]
I don't actually have any experience at all with any assembly, and especially not N64 assembly unfortunately.

**Comment by phixtyseven** [comment]
It's no problem. I'll continue to see what I can figure out from the wikis and previous commits. If I find an appropriate time and place to ask one of the other devs about it I may try that too.

**Pull request closed without merging**
