### PR TITLE
Add Minor Tricks

### PR DESCRIPTION
**Pull request by r0bd0g**
- BOTW Vanilla entry with nuts or boomerang.
- Go through the Forest Temple well with well-positioned hookshot.
- Clear GTG MQ with just Hookshot.
- Fire Temple MQ near-boss chest with Bombchu instead of Hookshot or Hover Boots.

I did not add the Spirit Temple Vanilla climb wall with nothing, but try it out.
(I'm assuming you'll want to try all of these out, though.)

Updated the readme to reflect these changes. Apparently I nuked the whitespace on the whole file, sorry.

### CODE REVIEW

**Comment by r0bd0g** [comment]
Oh, the rules file also include a line added by TR in his recent edits to remove GS tokens from shop locations due to a softlock.

**Comment by r0bd0g** [comment]
Update to required Goron Tunic for the new bombchu thing in fire temple. It's bad without it. And if fewer tunics there might not even be enough time.

**Comment by r0bd0g** [comment]
Also on that near boss goal I think the first fire source check is redundant since you 100% need fire to enter that room.

And just to note I guess, the 2nd edit to mq gtg does not need logic_tricks as you will always have longshot unless logic tricks is on.

**Comment by AmazingAmpharos** [comment]
I manually implemented this stuff as we discussed for the most part.

**Comment by r0bd0g** [comment]
I sent you a video with a new development on the fire temple mq box thing, though.
That box is actually 100% irrelevant, as long as you know it's irrelevant.

**Pull request closed without merging**
